services:
  backend:
    container_name: backend
    image: node:23.1.0
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/home/node/app
      - ./backend/node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    networks:
      - simple-blog-network
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: database
    image: postgres:15.9-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - simple-blog-network
    env_file:
      - .env

networks:
  simple-blog-network:
    name: simple-blog-network
    driver: bridge

volumes:
  db_data:
    name: db_data
  node_modules:
