services:
  backend: # Payload CMS backend
    container_name: backend
    image: node:18-alpine
    user: node
    ports:
      - '3000:3000'
    volumes:
      - ./payload:/home/node/app
      - ./payload/node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: database
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_data:
  node_modules:
